name: PlayerMilk
version: 0.5
main: com.ciallo.playermilk.PlayerMilk
author: ciallo
api-version: '1.21'
description: Right-click players with an empty bucket to milk them!

commands:
  playermilk:
    description: Main PlayerMilk command
    aliases: [pmilk]
    permission: playermilk.admin
    usage: /<command> [help|reload|toggle|about|set|effects]

permissions:
  playermilk.admin:
    description: Allows using PlayerMilk commands
    default: op